"""
Rebuilds app/growth_data.py from the WHO Child Growth Standards spreadsheets.

Download the four "expanded tables" (z-score) files from
  https://www.who.int/tools/child-growth-standards/standards/weight-for-age
  https://www.who.int/tools/child-growth-standards/standards/length-height-for-age
(weight-for-age and length/height-for-age, boys and girls, 0-5 years) into one
folder and run:

    pip install openpyxl
    python scripts/gen_growth_data.py path/to/that/folder

The sheets are recognised by their title (WFA_boys_z_exp, WFA_girls_z_exp,
LFA_boys_z_exp, LFA_girls_z_exp), so file names don't matter.
"""
import glob
import os
import sys

import openpyxl

OUT = os.path.join(os.path.dirname(__file__), "..", "app", "growth_data.py")
MAX_DAY = 1856
# Dense where the curves change fastest (first month) and around the day-730
# switch from lying length to standing height, sparse elsewhere; the app
# interpolates linearly between these knots.
DAYS = (
    list(range(0, 31))
    + list(range(35, 725, 7))
    + [727, 728, 729, 730, 731, 732, 735]
    + list(range(742, MAX_DAY, 28))
    + [MAX_DAY]
)

HEADER = '''"""
WHO Child Growth Standards (2006), birth to 5 years: the LMS parameters for
weight-for-age and length/height-for-age, boys and girls.

Source: WHO "Expanded tables for constructing national health cards" (z-score
tables, https://www.who.int/tools/child-growth-standards/standards). The
originals are day-by-day; they are sampled here (daily for the first month,
weekly up to age 2, every 4 weeks after) and app/reference_ranges.py
interpolates linearly between knots (the curves are smooth, so the error is
below 0.1%). Generated by scripts/gen_growth_data.py.

Each row is (age_days, L, M, S). A value X at that age has
    z = ((X / M) ** L - 1) / (L * S)          (L != 0)
and the value at a given z is  X = M * (1 + L * S * z) ** (1 / L).
M is the median. Weight is in kg, length in cm.
"""
'''


def rows_block(rows: dict) -> str:
    cells = [f"({d},{rows[d][0]:g},{rows[d][1]:g},{rows[d][2]:g})" for d in DAYS]
    return "\n".join("    " + ",".join(cells[i:i + 6]) + "," for i in range(0, len(cells), 6))


def main(folder: str) -> None:
    tables = {}
    for path in glob.glob(os.path.join(folder, "*.xlsx")):
        ws = openpyxl.load_workbook(path, data_only=True).active
        tables[ws.title] = {
            int(r[0]): (r[1], r[2], r[3]) for r in ws.iter_rows(min_row=2, values_only=True) if r[0] is not None
        }
    names = {
        "WFA_BOYS": "WFA_boys_z_exp",
        "WFA_GIRLS": "WFA_girls_z_exp",
        "LFA_BOYS": "LFA_boys_z_exp",
        "LFA_GIRLS": "LFA_girls_z_exp",
    }
    missing = [sheet for sheet in names.values() if sheet not in tables]
    if missing:
        sys.exit(f"Missing sheets in {folder}: {', '.join(missing)}")
    body = "\n".join(f"{var} = (\n{rows_block(tables[sheet])}\n)\n" for var, sheet in names.items())
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER + "\n# (age_days, L, M, S)\n" + body)
    print(f"wrote {os.path.normpath(OUT)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
